# Executes commands at login post-zshrc.

# Execute code that does not affect the current session in the background.
{
    # Compile the completion dump to increase startup speed.
    dump_file="$HOME/.zcompdump"
    if [[ "$dump_file" -nt "${dump_file}.zwc" || ! -s "${dump_file}.zwc" ]]; then
        zcompile "$dump_file"
    fi

    # Set environment variables for launchd processes.
    if [[ "$OSTYPE" == darwin* ]]; then
        if [[ -z "$TMUX" ]]; then
            for env_var in PATH MANPATH; do
                launchctl setenv "$env_var" "${(P)env_var}"
            done
        fi
    fi
} &!

# Set zsh-autosuggestions color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=214'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Clear autosuggestions when pasting to avoid confusion (the bracketed-paste-magic feature might be conflicting)
zstyle ':bracketed-paste-magic' active-widgets '.self-*'

# Bind zsh-history-substring-search keys
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
