#!/usr/bin/env bash

# Shortcuts
alias _="sudo"
alias g="git"
alias h="history"
alias rr="rm -rf"

# Default options
alias rsync="rsync -vh"

# Global aliases
alias G="| grep -i"
alias H="| head"
alias T="| tail"
alias L="| less"

# dir listing/traversal
alias l="ls -lahA"
alias la='ls -lAh'
alias ll="ls -lA"
alias lt="ls -lhAtr"
alias ld="ls -ld */"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd -"                  # Go to previous dir with -
alias cd.='cd $(readlink -f .)'    # Go to real dir (i.e. if current dir is linked)
alias tree="tree -A"
alias treed="tree -d"
alias tree1="tree -d -L 1"
alias tree2="tree -d -L 2"
alias cpwd="pwd|tr -d '\n'|pbcopy"

# npm
alias ni="npm install"
alias nun="npm uninstall"
alias nup="npm update && npm out"
alias nrr="find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +"

# Network
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"
alias ipl="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ifactive="ifconfig | awk '/^[a-z]/{iface=\$1} /status: active/{print iface}'"

# Logs
alias systail='log stream --style syslog'

# Recursively remove Apple meta files
alias cleanupds="find . -type f -name '*.DS_Store' -ls -exec /bin/rm {} \;"
alias cleanupad="find . -type d -name '.AppleD*' -ls -exec /bin/rm -r {} \;"
alias cleanup="cleanupds && cleanupad"

# Miscellaneous
alias quit="exit"
alias week="date +%V"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Update everything
alias update='bash ~/.dotfiles/macos/update.sh --no-defaults'

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"

# Empty the Trash on all mounted volumes and the main HDD.
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash"

# Clear Apple’s System Logs to improve shell startup speed. Clear download history from quarantine. https://mths.be/bum
alias clearlogs=" sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# URL-encode strings
alias urlencode='python3 -c "import sys, urllib.parse; print(urllib.parse.quote_plus(sys.argv[1]));"'

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Kill almost all of the running applications on the currently logged in user
alias rebootapps="launchctl reboot apps"

# Restart all user applications without rebooting the entire system
alias rebootuserspace="sudo launchctl reboot userspace"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Install a Node version via fnm and carry over global packages
# Usage: install_node [version]  e.g. install_node 20, install_node lts
install_node() { bash "$HOME/.dotfiles/scripts/install-node.sh" "$@"; }

# Diff global npm packages between two node versions
# Usage: npm_globals_diff <version_a> [version_b]  (version_b defaults to current node)
#   Versions can be a major (22), full string (v22.22.0), or lts
#   e.g. npm_globals_diff 22, npm_globals_diff lts 22
npm_globals_diff() { bash "$HOME/.dotfiles/scripts/npm-globals-diff.sh" "$@"; }
